## Simple appliance controlled via Sonoff S20 outlet
## and on the side, measure humidity, temperature and pressure via BME280
#===============================================================================
substitutions:
  device_name: dishwasher
  device_friendly_name: "Geschirrspuehler"
  room_friendly_name: "Kitchen"
#===============================================================================  

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret iotwifi_name
  password: !secret iotwifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_friendly_name} Hotspot"
    password: !secret fallbackwifi_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password

## i2c configuration
i2c:
  sda: 1
  scl: 3
  scan: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_friendly_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${device_friendly_name} Status"

switch:
  - platform: gpio
    name: "${device_friendly_name} Relay"
    pin: GPIO12
    id: relay

output:
  # Register the green LED as a dimmable output ....
  - platform: esp8266_pwm
    id: s20_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${device_friendly_name} Green LED"
    output: s20_green_led

#mqtt:
#    broker: !secret mqttpesta_broker
#    username: !secret mqttpesta_username
#    password: !secret mqttpesta_password


## sensor configuration
sensor:
  - platform: bme280
    temperature:
      name: "${room_friendly_name} Temperature"
      oversampling: 16x
    pressure:
      name: "${room_friendly_name} Pressure"
    humidity:
      name: "${room_friendly_name} Humidity"
    address: 0x76
    update_interval: 60s
