## - acts as BLE proxy
## - controls A/C via IR
## Waveshare ESP32 ETH CAM POE
#===============================================================================

#===============================================================================
substitutions:
  device_name: livingroom-cam-ble-ir
  room_friendly_name: Living Room
#===============================================================================

esphome:
  name: ${device_name}
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio
    upload_speed: 921600
    monitor_speed: 115200

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_S3_BOX_BOARD: "y"

psram:
  mode: octal
  speed: 80MHz


logger:

api:
  encryption:
    key: !secret api_encryption_psk

ota:
  - platform: esphome
    password: !secret ota_password

ethernet:
  type: W5500
  clk_pin: GPIO13
  mosi_pin: GPIO11
  miso_pin: GPIO12
  cs_pin: GPIO14
  interrupt_pin: GPIO10
  reset_pin: GPIO9



######################################
### Camera 
######################################

esp32_camera:
  name: ${room_friendly_name} Camera
  external_clock:
    pin: GPIO3
    frequency: 20MHz
  i2c_pins:
    sda: GPIO48
    scl: GPIO47
  data_pins: [GPIO41, GPIO45, GPIO46, GPIO42, GPIO40, GPIO38, GPIO15, GPIO18]
  vsync_pin: GPIO1
  href_pin: GPIO2
  pixel_clock_pin: GPIO39
    #reset_pin: GPIO8
  power_down_pin: GPIO8
  resolution: 640x480
  jpeg_quality: 10
    #resolution: 1280x1024
    #jpeg_quality: 30
  vertical_flip: false
  horizontal_mirror: false
  # aec_mode: MANUAL
  # aec_value: 1200
  # brightness: 2
  # wb_mode: HOME
  # agc_mode: AUTO



#######################################
### Bluetooth Proxy
#######################################

esp32_ble_tracker:
  scan_parameters:
    #  only use these values on Ethernet not WIFI
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true


#######################################
### Onboard WS2812
#######################################

light:
  - platform: esp32_rmt_led_strip
    id: led_light
    name: "${room_friendly_name} Notification Pixel 2"
    pin: 21
    num_leds: 1
    # rmt_channel: 1
    rgb_order: GRB
    chipset: ws2812
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
      - addressable_color_wipe:
