## Sonoff Pow R3
## which monitors and controls a electrical warmwater boiler heater
## see https://templates.blakadder.com/sonoff_POWR3.html for pinout

#===============================================================================
substitutions:
  device_name: boilerheater
  device_friendly_name: WarmwaterBoilerHeater
#===============================================================================

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  power_save_mode: none
  networks:
  - ssid: !secret p_mb_laurent_wifiiot_name
    password: !secret p_mb_laurent_wifiiot_pass
    priority: 9
  reboot_timeout: 6h
  fast_connect: true

# Disable logging
logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_psk
  reboot_timeout: 0s


ota:
  - platform: esphome
    password: !secret old_api_password

#mqtt:
#    broker: !secret mqttpesta_broker
#    username: !secret mqttpesta_username
#    password: !secret mqttpesta_password
#    discovery: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_friendly_name} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    pin:
      number: 12
      inverted: true
    id: relay
    icon: mdi:desktop-classic
    restore_mode: RESTORE_DEFAULT_OFF
    name: "${device_friendly_name}"

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: true

climate:
  - platform: bang_bang
    id: boilertemp_bangbang_regelung
    name: "Boilertemperaturregelung"
    sensor: warmwaterboiler_temp_sensor
    default_target_temperature_low: 38 °C
    default_target_temperature_high: 47 °C
    away_config:
      default_target_temperature_low: 12°C
      default_target_temperature_high: 15°C
    heat_action:
      - switch.turn_on: relay
    idle_action:
      - switch.turn_off: relay
    visual:
      min_temperature: 12
      max_temperature: 70

light:
  - platform: monochromatic
    name: ${device_friendly_name} Blue LED
    output: pow_blue_led
    id: blue_led

uart:
  rx_pin: RX
  baud_rate: 4800

# DS18b20 Sensor
one_wire:
  - platform: gpio
    pin: GPIO16 ## pin15 should not be pulled high on esp8266, it will not boot if CS-pin is high. thus the pullup is bad. maybe get vdd from somewhere else

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: cse7766
    current:
      name: ${device_friendly_name} Current
      icon: mdi:current-ac
    voltage:
      name: ${device_friendly_name} Voltage
      icon: mdi:flash
    energy:
      name: ${device_friendly_name} Energy
      icon: mdi:home-lightning-bolt-outline
    power:
      name: ${device_friendly_name} Power
      id: ${device_name}_wattage
      icon: mdi:gauge
      on_value:
        if:
          condition:
            sensor.in_range:
              id: ${device_name}_wattage
              above: 5.0
          then:
            - light.turn_on:
                id: blue_led
                brightness: !lambda |-
                  return 0.2+0.8*min(id(${device_name}_wattage).state*0.8/2600.0,0.8);
          else:
            - light.turn_off: blue_led
  - platform: total_daily_energy
    name: ${device_friendly_name} Total Daily Energy
    power_id: ${device_name}_wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: mdi:chart-bar
  - platform: wifi_signal
    name: "${device_friendly_name} WiFi Signal"
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    icon: mdi:wifi
  - platform: dallas_temp
    id: warmwaterboiler_temp_sensor
    name: "${device_friendly_name} Temperature"
    #update_interval: 10s

#  - platform: dallas_temp
#    #address: 0x1c0000031edd2a28
#    name: "Heizung Vorlauftemperatur"
#  - platform: dallas_temp
#    #address: 0x1c0000031edd2a28
#    name: "Heizung Rücklauftemperatur"

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80
