# I use this to pre-flash Athom 16A EUv2, so they can be quickly deployed later
# Homeassistant API and mqtt are disabled
# https://templates.blakadder.com/athom_PG01V2-EU16A-TAS
#===============================================================================
substitutions:
  device_name: newAthom
  device_friendly_name: "New"

#===============================================================================


esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

wifi:
  networks:
  - ssid: !secret iotwifi_name
    password: !secret iotwifi_pass
    priority: 10
  - ssid: !secret kilobaseriot_name
    password: !secret kilobaseriot_pass
    priority: 5
  - ssid: !secret realstuffwifi_name
    password: !secret realstuffwifi_pass
    priority: 3
  reboot_timeout: 5h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_friendly_name} Fallback Hotspot"
    password: !secret fallbackwifi_pass

captive_portal:

ota:
  password: !secret api_password

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO03
  baud_rate: 4800

web_server:
  port: 80

# Enable Home Assistant API
#api:
#  password: !secret api_password
#  reboot_timeout: 3h

sensor:
  - platform: cse7766
    current:
      name: "${device_friendly_name} Current"
      filters:
        - lambda: "return ((x < 0.5)? 0.0 : x);"
#        - calibrate_linear:
#            - 0 -> 0
#            - 2.48 -> 2.59
    voltage:
      name: "${device_friendly_name} Voltage"
      filters:
        offset: -1.1
    power:
      name: "${device_friendly_name} Power"
      filters:
        - lambda: "return ((x < 0.6)? 0.0 : x);"
#        - calibrate_linear:
#            - 0 -> 0
#            - 540 -> 573
    energy:
      name: "${device_friendly_name} Energy"
    update_interval: 20s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    name: "${device_friendly_name} Button"
    on_press:
      - switch.toggle: relayswitch
  - platform: status
    name: "${device_friendly_name} Status"

output:
  - platform: gpio
    pin: GPIO12
    id: relay

button:
  - platform: restart
    name: "Restart ${device_friendly_name}"

switch:
  - platform: output
    name: "${device_friendly_name} Relay"
    output: relay
    id: relayswitch

status_led:
  pin:
    number: GPIO13
    inverted: yes


#mqtt:
#    username: !secret mqttpesta_username
#    password: !secret mqttpesta_password
#    broker: !secret mqttpesta_broker
