## Control a GW60 blinds motor / rollandenmotor using a ZB35 remote hacked with an esp8266
## see https://realraum.at/wiki/doku.php?id=xro:rollohack_gw60
##
## the remote's buttons remain useable, by using the custom MyTriStateOutput class
#===============================================================================
substitutions:
  device_name: zb35remote
  device_friendly_name: "ZB35 Rollo Remote"
#===============================================================================

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  on_boot:
   - script.execute: rollo_set_gpio_to_input
   - script.wait: rollo_set_gpio_to_input
  includes:
    - gpio_tristate_output.h

wifi:
  ssid: !secret iotwifi_name
  password: !secret iotwifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} fallback"
    password: !secret fallbackwifi2_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_psk

ota:
  - platform: esphome
    password: !secret ota_password



output:
  - platform: custom
    type: float
    lambda: |-
      auto my_tristate_pin14 = new MyTriStateOutput(14); // D5
      App.register_component(my_tristate_pin14);
      return {my_tristate_pin14};
    outputs:
      id: gpio_zb35_b0

  - platform: custom
    type: float
    lambda: |-
      auto my_tristate_pin12 = new MyTriStateOutput(12); // D6
      App.register_component(my_tristate_pin12);
      return {my_tristate_pin12};
    outputs:
      id: gpio_zb35_b1

  - platform: custom
    type: float
    lambda: |-
      auto my_tristate_pin13 = new MyTriStateOutput(13); // D7
      App.register_component(my_tristate_pin13);
      return {my_tristate_pin13};
    outputs:
      id: gpio_zb35_b2

  - platform: custom
    type: float
    lambda: |-
      auto my_tristate_pin15 = new MyTriStateOutput(15); // D8
      App.register_component(my_tristate_pin15);
      return {my_tristate_pin15};
    outputs:
      id: gpio_zb35_b3


script:
  - id: rollo_set_gpio_to_input
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b0
          level: 50%
      - output.set_level:
          id: gpio_zb35_b1
          level: 50%
      - output.set_level:
          id: gpio_zb35_b2
          level: 50%
      - output.set_level:
          id: gpio_zb35_b3
          level: 50%
  - id: rollo_up
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b0
          level: 100%
      - output.set_level:
          id: gpio_zb35_b1
          level: 0%
      - delay: 1500ms
  - id: rollo_down
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b0
          level: 0%
      - output.set_level:
          id: gpio_zb35_b1
          level: 100%
      - delay: 1500ms
  - id: rollo_stop
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b0
          level: 100%
      - output.set_level:
          id: gpio_zb35_b1
          level: 100%
      - delay: 1500ms
  - id: rollo_select_0
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b2
          level: 0%
      - output.set_level:
          id: gpio_zb35_b3
          level: 0%
  - id: rollo_select_1
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b2
          level: 100%
      - output.set_level:
          id: gpio_zb35_b3
          level: 0%
  - id: rollo_select_2
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b2
          level: 0%
      - output.set_level:
          id: gpio_zb35_b3
          level: 100%
  - id: rollo_select_3
    mode: single
    then:
      - output.set_level:
          id: gpio_zb35_b2
          level: 100%
      - output.set_level:
          id: gpio_zb35_b3
          level: 100%

cover:
  - platform: template
    optimistic: true
    assumed_state: true
    has_position: false
    device_class: shutter
    id: rollo_all
    name: zb35_rollo_all
    open_action:
      - script.execute: rollo_select_0
      - script.wait: rollo_select_0
      - script.execute: rollo_up
      - script.wait: rollo_up
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    close_action:
      - script.execute: rollo_select_0
      - script.wait: rollo_select_0
      - script.execute: rollo_down
      - script.wait: rollo_down
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    stop_action:
      - script.execute: rollo_select_0
      - script.wait: rollo_select_0
      - script.execute: rollo_stop
      - script.wait: rollo_stop
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input

  - platform: template
    optimistic: true
    assumed_state: true
    has_position: false
    device_class: shutter
    id: rollo1
    name: zb35_rollo_1
    open_action:
      - script.execute: rollo_select_1
      - script.wait: rollo_select_1
      - script.execute: rollo_up
      - script.wait: rollo_up
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    close_action:
      - script.execute: rollo_select_1
      - script.wait: rollo_select_1
      - script.execute: rollo_down
      - script.wait: rollo_down
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    stop_action:
      - script.execute: rollo_select_1
      - script.wait: rollo_select_1
      - script.execute: rollo_stop
      - script.wait: rollo_stop
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input

  - platform: template
    optimistic: true
    assumed_state: true
    has_position: false
    device_class: shutter
    id: rollo2
    name: zb35_rollo_2
    open_action:
      - script.execute: rollo_select_2
      - script.wait: rollo_select_2
      - script.execute: rollo_up
      - script.wait: rollo_up
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    close_action:
      - script.execute: rollo_select_2
      - script.wait: rollo_select_2
      - script.execute: rollo_down
      - script.wait: rollo_down
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    stop_action:
      - script.execute: rollo_select_2
      - script.wait: rollo_select_2
      - script.execute: rollo_stop
      - script.wait: rollo_stop
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input

  - platform: template
    optimistic: true
    assumed_state: true
    has_position: false
    device_class: shutter
    id: rollo3
    name: zb35_rollo_3
    open_action:
      - script.execute: rollo_select_3
      - script.wait: rollo_select_3
      - script.execute: rollo_up
      - script.wait: rollo_up
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    close_action:
      - script.execute: rollo_select_3
      - script.wait: rollo_select_3
      - script.execute: rollo_down
      - script.wait: rollo_down
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
    stop_action:
      - script.execute: rollo_select_3
      - script.wait: rollo_select_3
      - script.execute: rollo_stop
      - script.wait: rollo_stop
      - script.execute: rollo_set_gpio_to_input
      - script.wait: rollo_set_gpio_to_input
